
###
GET http://localhost:8085/a/test?value1=1&value2=2
Authorization: Basic YWRta

###
GET http://localhost:8085/b/test

###
GET http://localhost:8085/b/ret

### Запрос с ошибкой
GET http://localhost:8085/a/err
